---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      creationTimestamp:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: password
        image: hiroosakihal/gitops-app-test:f6a539a68ad342cc21bfa93bddeb6a24410d17cd
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
